### ISSUE TITLE
Have `TBLIS.set_num_threads(n)` return the current number of threads

### ISSUE THREAD

**Issue by mtfishman** [FermiQC/TBLIS.jl#8]
As a follow up to #6, a useful feature would be to make `TBLIS.set_num_threads(n)` return the current number of threads, so that you could do:
```julia
original_tblis_threads = TBLIS.set_num_threads(4)
# Do a calculation with a 4 TBLIS threads
# Then reset to the original number of threads
TBLIS.set_num_threads(original_tblis_threads)
```

**Comment by gustavojra** [comment]
Would not a `TBLIS.nthreads()` do the job?
```
original_tblis_threads = TBLIS.nthreads()
TBLIS.set_num_threads(4)
# Do a calculation with a 4 TBLIS threads
# Then reset to the original number of threads
TBLIS.set_num_threads(original_tblis_threads)
```

**Comment by mtfishman** [comment]
Yes, there is already `TBLIS.get_num_threads()` that was added in #6 that would let you do:
```julia
original_tblis_threads = TBLIS.get_num_threads()
TBLIS.set_num_threads(4)
# TBLIS calculation using 4 threads
TBLIS.set_num_threads(original_tblis_threads)
```
(I chose `TBLIS.get_num_threads()` instead of `TBLIS.nthreads()` since it matches with the function `BLAS.get_num_threads()` that is being added in Julia 1.6). The suggested behavior in the first post would just be slightly more convenient since this is a common code pattern.

**Comment by gustavojra** [comment]
Ok! If you have the time, submit a pull request for it.

**Comment by gustavojra** [comment]
Done #10
